spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres?user=postgres.lzvrluetrrrfkkjhuhfa&password=Vishnu@2006_mashalkar
spring.datasource.username=postgres.lzvrluetrrrfkkjhuhfa
spring.datasource.password=Vishnu@2006_mashalkar
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5
logging.level.root=OFF
logging.level.com.example.campus_events=INFO
logging.file.name=${user.home}/Desktop/campus-event-management-system/campus-events/logs/eventara.log