spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.lzvrluetrrrfkkjhuhfa
spring.datasource.password=Vishnu@2006_mashalkar
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
logging.level.root=OFF
logging.level.com.example.campus_events=INFO
logging.file.name=${user.home}/Desktop/campus-event-management-system/campus-events/logs/eventara.log
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vishnumashalkar.cs24@bmsce.ac.in
spring.mail.password=Vachu1201
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
cloudinary.cloud-name=dfkdhpnve
cloudinary.api-key=751687722754291
cloudinary.api-secret=7nkcOpalB7HZ8v-EJcF1mCerCCE
spring.datasource.hikari.data-source-properties.prepareThreshold=0
spring.datasource.hikari.data-source-properties.binaryTransfer=false
server.port=${PORT:8080}
